---
title: "Social Effects on Fitness"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70),tidy=TRUE)
```

#Load Packages and Connections

```{r load packages and connections, message=FALSE}
# analysis
library (lme4)
library (lmerTest)
library (DHARMa)
```

# Load Data
```{r}
load("./data/Social_Fitness_Data.RData")
```


# Main Analysis

## Survival

```{r}
# Survival model 1
## Table 2
# Random slopes
summary(survival.1<-glmer(survived~age+I(age^2)+grid+std_soc_surv3*mast+(std_soc_surv3||year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))

#summary(glmer(survived~age+I(age^2)+grid+std_soc_surv3+(std_soc_surv3||year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, subset=mast=="y", control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# Did not converge

# no random slopes for mast years individually
summary(glmer(survived~age+I(age^2)+grid+std_soc_surv3+(1|year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, subset=mast=="y", control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))

summary(glmer(survived~age+I(age^2)+grid+std_soc_surv3+(std_soc_surv3||year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, subset=mast=="n", control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))


# no random slopes
summary(glmer(survived~age+I(age^2)+grid+std_soc_surv3*mast+(1|year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
```

### Model diagnostics
```{r}
# survival.1

testDispersion(survival.1)
simulation_output_survival.1<-simulateResiduals(fittedModel = survival.1, n = 250)
plot(simulation_output_survival.1)
testUniformity(simulation_output_survival.1)
testOutliers(simulation_output_survival.1)
# note that some of these diagnostics are significant but the same size is very large and the deviations from expectation are very small.
testDispersion(simulation_output_survival.1)
testZeroInflation(simulation_output_survival.1)

plotResiduals(simulation_output_survival.1, form = census_final$mast)
plotResiduals(simulation_output_survival.1, form = census_final$social_survival2)
```




## Reproductive Success Model

```{r Table 3}
# Table 3

###############
# Final Model #
###############
summary(reproduction.1<-glmer(all_litters_fit~age+I(age^2)+grid+std_soc_surv3*mast+std_soc_repro*mast+(std_soc_surv3+std_soc_repro||year)+(1|squirrel_id), data=census_final, family=poisson, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# converged: random intercept and random slopes but no correlation estimated between random slopes and intercept


##############################
# Other random slopes models #
##############################

### Full random slopes model
#summary(glmer(all_litters_fit~age+I(age^2)+grid+std_soc_surv3*mast+std_soc_repro*mast+(std_soc_surv3+std_soc_repro|year)+(1|squirrel_id), data=census_final, family=poisson, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# Did not converge: variation in soc_surv slopes is low and correlation between random slopes and random slopes is -1

# Two intercepts and random slopes
#summary(glmer(all_litters_fit~age+I(age^2)+grid+std_soc_surv3*mast+std_soc_repro*mast+(std_soc_surv3|year)+(std_soc_repro|year)+(1|squirrel_id), data=census_final, family=poisson, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# Did not converge

# Random slope for soc_repro allowed to covary with the random intercept but the random slope for soc_surv3 is independent of the random year intercept.
summary(glmer(all_litters_fit~age+I(age^2)+grid+std_soc_surv3*mast+std_soc_repro*mast+(0+std_soc_surv3|year)+(std_soc_repro|year)+(1|squirrel_id), data=census_final, family=poisson, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# converged


summary(glmer(all_litters_fit~age+I(age^2)+grid+std_soc_surv3*mast+std_soc_repro*mast+(std_soc_surv3|year)+(0+std_soc_repro|year)+(1|squirrel_id), data=census_final, family=poisson, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# converged

```


### Model diagnostics
```{r}
testDispersion(reproduction.1)
simulation_output_reproduction.1<-simulateResiduals(fittedModel = reproduction.1, n = 250)
plot(simulation_output_reproduction.1)
testUniformity(simulation_output_reproduction.1)
testOutliers(simulation_output_reproduction.1)

testDispersion(simulation_output_reproduction.1)
testZeroInflation(simulation_output_reproduction.1)

plotResiduals(simulation_output_reproduction.1, form = subset(census_final$mast, !is.na(census_final$all_litters_fit)))
plotResiduals(simulation_output_reproduction.1, form = subset(census_final$social_repro, !is.na(census_final$all_litters_fit)))

```




# Supplemental Analyses

### Distance-weighted Mortalities
```{r Table S1}

summary(survival.S1<-glmer(survived~age+I(age^2)+grid+std_soc_surv2*mast+(1|year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# random slopes models did not converge.  random slope variance was very low.


#summary(glmer(survived~age+I(age^2)+grid+std_soc_surv2*mast+(std_soc_surv2||year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
# Did not converge
```


### Distance-weighted Survival

```{r Table S2}
# Table S2
summary(survival.S2<-glmer(survived~age+I(age^2)+grid+std_soc_surv*mast+(std_soc_surv||year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))

# no random slopes
summary(glmer(survived~age+I(age^2)+grid+std_soc_surv*mast+(1|year)+(1|squirrel_id), data=census_final, family=binomial, na.action=na.omit, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
```


### Analyses without SU 2008 Data

```{r Table SX}
# Table SX
summary(glmer(all_litters_fit~age+I(age^2)+grid+std_soc_surv3*mast+std_soc_repro*mast+(std_soc_repro+std_soc_surv3||year)+(1|squirrel_id), data=census_final, family=poisson, subset=!(year==2008&grid=="SU"), control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))))
```


### Permutation Tests
TO BE ADDED
```{r}

```

